### ISSUE TITLE
Check repair mode 19,22

### ISSUE THREAD

**Issue by pinterf** [pinterf/RgTools#4]
Why repair mode 19 is the same as mode 22 while ordinary rg is different.
Check mode 19 and 22 rg and repair mode similarity.

**Comment by realfinder** [comment]
```
ColorBars(width=640, height=480, pixel_type="RGB32")
ConvertToYV12
AddGrainC(constant=true).AddGrainC(constant=true).AddGrainC(constant=true).AddGrainC(constant=true)
Blur(1).repair(last,22).mt_makediff(Blur(1).repair(last,19),u=3,v=3)
```
from what can I see they are not same

**Comment by pinterf** [comment]
You are right. The code differs: mode19 is using the center pixel, 22 is using the alternative clip pixel as the comparison reference. Where have I put my eyes?

**Comment by pinterf** [comment]
And thanks for checking it
