### ISSUE TITLE
RemoveGrain(19) produce all-green output for a 10-bit input clip

### ISSUE THREAD

**Issue by vasyl-zabolotniy** [pinterf/RgTools#5]
10-bit 420/422 source => removegrain(19) => green colored clip
video test sample: 
https://drive.google.com/file/d/1mv2LF5cRKNSryofY75fuV0teBQUBbEmW/view?usp=sharing

**Comment by pinterf** [comment]
Already fixed on git (December 2020), did not make a release yet.

**Comment by pinterf** [comment]
Released
